version: '3.3'

services:
  postgres:
    image: postgres:10.1-alpine
    build:
      context: db_init
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    container_name: postgres
    ports:
      - 5432:5432
    restart: always
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name:
      yaback_service
    ports:
      - 8080:8080
    tty: true
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data: